// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIx7-7xtAoCjhJUxqsIHL9tN_f9EVn8Bk',
    appId: '1:1038932243642:web:796e5157855e751a2f7e83',
    messagingSenderId: '1038932243642',
    projectId: 'app-chat-43c92',
    authDomain: 'app-chat-43c92.firebaseapp.com',
    storageBucket: 'app-chat-43c92.appspot.com',
    measurementId: 'G-FG5L018YY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkRq4IuaYMxHylQUtS5DD6KK9zWsRKvKg',
    appId: '1:1038932243642:android:ff39c2a89d1335422f7e83',
    messagingSenderId: '1038932243642',
    projectId: 'app-chat-43c92',
    storageBucket: 'app-chat-43c92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv3_t7bpD9AK-klgFzPeATIvIyqebHbQ0',
    appId: '1:1038932243642:ios:6b2b5cf85a411a022f7e83',
    messagingSenderId: '1038932243642',
    projectId: 'app-chat-43c92',
    storageBucket: 'app-chat-43c92.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv3_t7bpD9AK-klgFzPeATIvIyqebHbQ0',
    appId: '1:1038932243642:ios:6b2b5cf85a411a022f7e83',
    messagingSenderId: '1038932243642',
    projectId: 'app-chat-43c92',
    storageBucket: 'app-chat-43c92.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIx7-7xtAoCjhJUxqsIHL9tN_f9EVn8Bk',
    appId: '1:1038932243642:web:1e71ff54c12d0bab2f7e83',
    messagingSenderId: '1038932243642',
    projectId: 'app-chat-43c92',
    authDomain: 'app-chat-43c92.firebaseapp.com',
    storageBucket: 'app-chat-43c92.appspot.com',
    measurementId: 'G-Y5KXNXFV6G',
  );
}
